---
title: "rnoaa"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
# install.packages("dataRetrieval")
library(dataRetrieval) # for getting USGS NWIS data
# install.packages("tidyhydat")
library(tidyhydat) # for getting ECCC HYDAT data
# download_hydat()
library(dplyr) # for data wrangling and pipelines
library(ggplot2) # for modifying fasstr plots
library("dplyr")
#install.packages('corrplot')
library(corrplot)
library(RColorBrewer)
# install.packages("gbm")
library("gbm")
# install.packages("caret")
library("caret")
#install.packages("pdp")
library("pdp")          # model visualization
library("ggplot2")      # model visualization
#install.packages("lime")
library("lime")         # model visualization
library("pROC")
#install.packages("e1071", repos="http://R-Forge.R-project.org")
library("e1071")
library( "MASS" )    #    used to generate correlated variables
library("sp")
library("Hmisc")    #   used for graphing se bars
#install.packages("randomForest")
require("randomForest")
#install.packages("e1071")
library(e1071)
library(caret)
library("ModelMetrics")
library("foreign")
#install.packages("rfUtilities")
library("rfUtilities")
library("lubridate")
```

```{r}
met<-read.csv("3208490.csv")
```

```{r}
#met<-met[,c("TMAX","SNWD","PRCP","DATE","ELEVATION")]
#met_t<-met[!is.na(met$TMAX),]
#unique(met_t$NAME) # "BOISE AIR TERMINAL, ID US"   "BOISE 7 N, ID US"
met<-met[met$NAME=="BOISE AIR TERMINAL, ID US",]
summary(met)
```

```{r}
st_all_gage<-c("13211205")
#create empty tables
meanSummerT_df<-data.frame(
  agency_cd= " ",
  site_no="",
  Date=as.Date("1951-01-01",format="%Y-%m-%d"),
 # X_00010_00001=0,
#  X_00010_00001_cd=0,
  X_00010_00003=0,
  X_00010_00003_cd= "",
  X_00060_00003=0,    
  X_00060_00003_cd= "",
  yr="",
  mo=0


  )
for (id in st_all_gage) {
  siteNumber <-  id 
  parameterCd <- c("00010","00060") 
  #00060: Discharge, cubic feet per second
  #00010	Physical	Temperature, water, degrees Celsius	
  ChoptankInfo <- readNWISsite(siteNumber)
 #ChoptankInfo$alt_va : Gage datum feet above NGVD29
  #statCd <- c("00003") 
  #00001 max
  #00003 mean
  startDate <- "2015-10-01"
  endDate <- "2022-09-30"
  meanT <-readNWISdv(siteNumber, parameterCd,startDate, endDate, statCd= c("00001","00003"))
  if (dim(meanT )[2]>5){
    meanT$yr<- format(meanT$Date, format = "%Y") 
    meanT$mo<-as.numeric(format(meanT$Date, format = "%m"))
    meanSummerT<-meanT[ ,c("agency_cd","site_no","Date"
                       #    ,"X_00010_00001"
                      #     ,"X_00010_00001_cd"
                           ,"X_00010_00003","X_00010_00003_cd","X_00060_00003","X_00060_00003_cd","yr","mo"  )]
#    meanAugT<-meanT[meanT$mo==8,c("agency_cd","site_no","Date","X_00010_00001","X_00010_00001_cd","X_00010_00003","X_00010_00003_cd","X_00060_00003","X_00060_00003_cd","yr","mo"  )]

    
    meanSummerT_df <-rbind(meanSummerT_df,meanSummerT)
    print(    paste(id,dim(meanT )[1],Sys.time() ) )
  }
}
```

```{r}
df<-meanSummerT_df[ !is.na(meanSummerT_df$X_00010_00003),]
summary(df)
#save( df, file="USGS13211205_ST_Q.Rdata")
```

```{r}
met$date<-as.Date(met$DATE, format="%Y-%m-%d") 

df$date<-as.Date( df$Date, format="%Y-%m-%d") 
met_df<-merge(met,df,by.x = "date" ,by.y = "date")

met_df$X_00010_00003-> met_df$mean_StreamTemp
log(met_df$X_00060_00003)->met_df$log_median_Q
met_df$TMAX ->met_df$max_AirTemperature_C
met_df$doy<-yday( met_df$date)

met_df<-met_df[,c("date","max_AirTemperature_C","mean_StreamTemp","log_median_Q","mo","yr","doy")]

daily_df_summer<-met_df[month(met_df$date) %in% c(6,7,8),]

#save(daily_df_summer,file="Boise_daily_df_summer.Rdata")
```

```{r}
load( "Boise_daily_df_summer.Rdata"  )
load(  "USGS13211205_ST_Q.Rdata"  )
```


```{r}
M <-cor( daily_df_summer[,c("max_AirTemperature_C","mean_StreamTemp","log_median_Q", "doy")])
corrplot(M, type="upper", order="hclust",
         col=brewer.pal(n=8, name="RdYlBu"))
```

# Model 2: GBM
```{r}
# set seed for generating random data.
set.seed(0)          
# createDataPartition() function from the caret package to split the original dataset into a training and testing set and split data into training (80%) and testing set (20%)
variables<-c("mean_StreamTemp","max_AirTemperature_C", "log_median_Q", "doy")
parts = createDataPartition(  daily_df_summer$mean_StreamTemp , p = .8, list = F)
train = daily_df_summer[parts, variables ]
test =  daily_df_summer[-parts, variables  ]
# feature and target array
test_x = test[, -1] 
test_y = test[, 1] 
```

# Model 1: lm
```{r}
lm<-lm( mean_StreamTemp ~log_median_Q #+min_Discharge
        +max_AirTemperature_C +doy , data =  train  )
summary(lm)
RMSE = sqrt(mean(lm$residuals^2))
cat('The root mean square error of the test data is ', round(RMSE,3),'\n')
predict<-predict(lm, test_x)
summary(test_y)
xmin=5
xmax=30
x=seq(xmin-5,xmax+5)
plot( test_y ,predict,xlim=c(xmin,xmax) ,ylim=c(xmin,xmax), xlab="Observed stream temperature (degC)", ylab="Predicted stream temperature (degC)")
par(new=T)
plot(x,x,type="l",xlim=c(xmin,xmax) ,ylim=c(xmin,xmax),xlab="",ylab="", main="LM")
```

```{r}
model_gbm = gbm(train$mean_StreamTemp      ~.,
                data = train,
                distribution = "gaussian",
                cv.folds = 10,
                shrinkage = .01,
                n.minobsinnode = 10,
                n.trees = 800)
 
# model performance
perf_gbm1 = gbm.perf( model_gbm, method = "cv")
print(model_gbm)
summary(model_gbm)
rinf<-summary(model_gbm)
barplot( rinf$rel.inf , horiz = TRUE, las = 1)
ggplot(rinf, aes(rel.inf)) + geom_bar()
```

```{r}
rinf$var<- factor(rinf$var, levels=c(  "max_AirTemperature_C" ,"log_median_Q"
, "doy"  ))
ggplot( rinf, aes( var , rel.inf ))+  geom_col()+ 
  coord_flip()
ggplot( rinf )+  geom_bar(  aes( x=var, y= rel.inf),  stat = "summary")+ scale_x_discrete(labels=  c( "max_AirTemperature_C" ,"log_median_Q"
, "doy") )+ylab("Relative importance (%)") +xlab(" ")  + theme(text=element_text(size=11))
```

```{r}
#test_y <-test_y$max_StreamTemp
pred_y = predict.gbm(model_gbm, test_x)
residuals =  test_y   - pred_y
summary(test_y )
xlim=c(10,30)
RMSE = sqrt(mean(residuals^2))
cat('The root mean square error of the test data is ', round(RMSE,3),'\n')
y_test_mean = mean( test_y  )
# Calculate total sum of squares
tss =  sum(( test_y   - y_test_mean)^2 )
# Calculate residual sum of squares
rss =  sum(residuals^2)
# Calculate R-squared
rsq  =  1 - (rss/tss)
cat('The R-square of the test data is ', round(rsq,3), '\n')
# visualize the model, actual and predicted data
x_ax = 1:length(pred_y)
plot(x_ax, test_y  , col="blue", pch=20, cex=.9)
lines(x_ax, pred_y, col="red", pch=20, cex=.9) 
plot(  test_y , pred_y,xlim= xlim ,ylim= xlim, xlab="Observed stream temperature (degC)", ylab="Predicted stream temperature (degC)", main="GBM")
par(new=T)
x=seq(1,30)
plot(x,x,type="l",xlim= xlim ,ylim= xlim,xlab="",ylab="")
```

```{r}
model_gbm %>%
  partial(pred.var =  "max_AirTemperature_C"   , n.trees = model_gbm$n.trees, grid.resolution = 100) %>%
  autoplot(rug = TRUE, train = train)+theme(axis.text=element_text(size=21),
        axis.title=element_text(size=24))
#,"min_Discharge"
model_gbm %>%
  partial(pred.var =  "log_median_Q"
             #,"min_Discharge"
               , n.trees = model_gbm$n.trees, grid.resolution = 100) %>%
  autoplot(rug = TRUE, train = train)+theme(axis.text=element_text(size=21),
        axis.title=element_text(size=24))
```

```{r}

```




